import type { Metadata } from "next";
import { Exo_2, Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { Footer } from "@/components/Footer";

const robotoSans = Montserrat({
   variable: "--font-roboto-sans",
   subsets: ["latin"],
});

const exo2 = Exo_2({
   variable: "--font-exo-sans",
   subsets: ["latin"],
});


export const metadata: Metadata = {
   title: "Асфальтирование в Волгограде",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={cn("h-full", "antialiased", robotoSans.variable, exo2.variable, "font-sans")}
      >
         <body className="">
            {children}
            <Toaster position="bottom-center" />
            <Footer />
         </body>
      </html>
   );
}
