import type { Metadata } from "next";
import { Exo_2, Roboto } from "next/font/google";
import "./globals.css";
import { SmoothScrollProvider } from "@/components/smooth-scroll-provider";

const robotoSans = Roboto({
   variable: "--font-roboto-sans",
   subsets: ["latin"],
});

const exo2 = Exo_2({
   variable: "--font-exo-sans",
   subsets: ["latin"],
});


export const metadata: Metadata = {
   title: "Асфальтирование в Волгограде",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={`${robotoSans.variable} ${exo2.variable} h-full antialiased`}
      >
         <body className="min-h-full flex flex-col">
            <SmoothScrollProvider>
               {children}
            </SmoothScrollProvider>
         </body>
      </html>
   );
}
